on:
  push:
    branches:
#      - 'main'
      - 'release/*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.100
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
#      - name: Test
#        run: dotnet test --no-restore --verbosity normal
      - name: Pack
        run: dotnet pack --configuration Release -o pack --no-build
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: nupkg
          path: pack
      - name: Push to NuGet
        if: ${{ github.repository == 'Khitiara/MediatingApis' && startsWith(github.ref, 'refs/heads/release/') }}
        run: dotnet nuget push pack\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org